### PR TITLE
Avoid failing date format when there's no year ( closes #234 )

### LINKED ISSUE #234: Strange appearance from birthdays without a year
### Steps to reproduce

In the default contacts app ( on GrapheneOS ) a birthday without a year is displayed like this for example: 7. Oktober.

In Connect You it is displayed like this: --10-07.

### Expected behavior

See above...

### Actual behavior

See above...

### Connect You version

6.0

### Android version

13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by SuhasDissa**

### CODE REVIEW

File: app/src/main/java/com/bnyro/contacts/util/CalendarUtils.kt [hunk 1]
```diff
@@ -22,10 +25,24 @@ object CalendarUtils {
     fun dateToMillis(date: String) = isoDateFormat.parse(date)?.time
 
     fun localizeIsoDate(isoDate: String): String {
+        val noYear = isoDate.startsWith('-')
```
Comment (Bnyro) [inline app/src/main/java/com/bnyro/contacts/util/CalendarUtils.kt:28]:
```suggestion
        val isDateWithoutYear = isoDate.startsWith('-')
```

File: app/src/main/java/com/bnyro/contacts/util/CalendarUtils.kt [hunk 2]
```diff
@@ -22,10 +25,24 @@ object CalendarUtils {
...
+        val newIsoDate = if (noYear) isoDate.replace("--", "") else isoDate
+
```
Comment (Bnyro) [inline app/src/main/java/com/bnyro/contacts/util/CalendarUtils.kt:30]:
```suggestion
val formatter = if (isDateWithoutYear) isoDateFormtWithoutYear we isoDateFormat
```

File: app/src/main/java/com/bnyro/contacts/util/CalendarUtils.kt [hunk 3]
```diff
@@ -22,10 +25,24 @@ object CalendarUtils {
...
         val date = runCatching {
-            isoDateFormat.parse(isoDate) ?: return isoDate
-        }.getOrNull() ?: return isoDate
-        return localizedFormat.format(date) ?: isoDate
+            if (noYear) {
+                isoDateFormatWithoutYear.parse(newIsoDate)
+            } else {
+                isoDateFormat.parse(isoDate)
+            } ?: return newIsoDate
```
Comment (Bnyro) [inline app/src/main/java/com/bnyro/contacts/util/CalendarUtils.kt:36]:
```suggestion
            }
```

File: app/src/main/java/com/bnyro/contacts/util/CalendarUtils.kt [hunk 4]
```diff
@@ -22,10 +25,24 @@ object CalendarUtils {
...
+        }.getOrNull() ?: return newIsoDate
+        return localizedFormat.format(date).let {
+            if (noYear) {
+                // Due to the limitations of the API we're getting 1970 when there's no year
+                it.replace("1970", "")
+            } else {
+                it
+            }
+        } ?: newIsoDate
```
Comment (Bnyro) [inline app/src/main/java/com/bnyro/contacts/util/CalendarUtils.kt:45]: I don't think anything could be null here (otherwise we should do `localizedFormat(date)?.let {`

**Comment by Bnyro** [comment]
The approach looks good to me in general, just some minor things to make the code look more simple.

**Review by Bnyro — APPROVED** [review]
